project_id: '491513'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
  # JSON translation files
  {
    source: '/i18n/languages/backend_en.json',
    translation: '/i18n/languages/*.json',
  },
]
