version: '3.1'
services:
  casdoor:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "BUILLD_LOCATION=CN"
    environment:
      - "CASDOOR_DATA_SOURCE=root:123456@tcp(db:3306)/"
      - "CASDOOR_DATA_DRIVER=mysql"
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - db
    #  !!import!! if you want set multiple config you can bind volume and delete environment
    # volumes:
    #   - ./conf:/conf/
  db:
    restart: always
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - data:/var/lib/mysql
  # db:
  #   restart: always
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_USER: root
  #     POSTGRES_DB: casdoor
    # volumes:
    #   - data:/var/lib/postgresql/data    
volumes:
  data: