mysql:
  -
    host: "120.27.146.138"
    port: 3306
    username: "root"
    password: "admin"
    database: "myDb"
    base: "charset=utf8mb4&parseTime=True&loc=Local"

  -
    host: "121.40.240.136"
    port: 3306
    username: "root"
    password: "admin"
    database: "myDb"
    base: "charset=utf8mb4&parseTime=True&loc=Local"