version: '3.1'
services:
  testing:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GITHUB_TOKEN: "$GITHUB_TOKEN"
      PULL_REQUEST: "$PULL_REQUEST"
      SERVER: "http://casdoor:8000"
    links:
      - casdoor
    depends_on:
      casdoor:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  casdoor:
    restart: always
    image: casbin/casdoor
    entrypoint: /bin/sh -c './server --createDatabase=true'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RUNNING_IN_DOCKER: "true"
      dataSourceName: root:123456@tcp(db:3306)/
  db:
    restart: always
    image: mysql:8.0.25
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: 123456
