name: Helm Release

on:
  push:
    branches:
      - master
    paths:
      - 'manifests/casdoor/Chart.yaml'

jobs:
  release-helm-chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Release Helm Chart
        run: |
          cd manifests/casdoor
          helm package .
          PKG_NAME=$(ls *.tgz)
          helm repo index . --url oci://registry-1.docker.io/casbin/casdoor-helm-charts --merge index.yaml
          helm push $PKG_NAME oci://registry-1.docker.io/casbin/casdoor-helm-charts

      - name: Commit updated helm index.yaml
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci: update helm index.yaml'
          file_pattern: index.yaml