name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ dckr_pat_wmh50-vtqmrF0K1LYYqIJvQOXXo }}" | docker login --username "${{ onedot911 }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t onedot911/casdoor:latest .
        docker push onedot911/casdoor:latest
